<?php

/**
 * PluginPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPost');
    }
}