<?php

/**
 * PluginUnLikeOnShareTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUnLikeOnShareTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUnLikeOnShareTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUnLikeOnShare');
    }
}