<?php

/**
 * PluginPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPost extends BasePost {

    protected $buzzConfigService;

    public function getEmployeeFirstLastName() {
        if ($this->getEmployeeNumber() != '') {
            return $this->getEmployeePostAdded()->getFirstAndLastNames();
        } else {
            return 'Admin';
        }
    }

    /**
     * 
     * @return BuzzConfigService
     */
    private function getBuzzConfigService() {
        if (!$this->buzzConfigService) {
            $this->buzzConfigService = new BuzzConfigService();
        }

        return $this->buzzConfigService;
    }

    public function getDate() {
        return set_datepicker_date_format($this->getPostTime());
    }

    public function getTime() {
        $timeFormat = $this->getBuzzConfigService()->getTimeFormat();
        return date($timeFormat, strtotime($this->getPostTime()));
    }

}
