<?php

/**
 * PluginUnLikeOnCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginUnLikeOnCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginUnLikeOnCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginUnLikeOnComment');
    }
}