plugin_name: orangehrmBuzzPlugin  
dbscript_path: install/dbscript.sql    
symfony_commands: { 0: php symfony orangehrm:publish-assets,1: php symfony doctrine:build-model,2: php symfony cc}  
dependencies:   
  plugins:  
    depends:  
    install-after: []  
    conflicts: []  
    replaces: []  