buzz:
  name: Orange Buzz
  url: 'buzz/viewBuzz'
  plugin: orangehrmBuzzPlugin
  target: '_blank'
  image: 'orange.png'
  requiredPermissions: {'data_group': {'buzz_link': {'canRead': true, 'canCreate': false, 'canUpdate': false, 'canDelete': false}}}
  ohrm_module: 'buzz'
