methods:
  getLatestBuzzShares:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: GET 
  getBuzzShares:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: GET      
  getMoreBuzzShares:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: GET
  getShareAndPostDetailsByShareId:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: GET 
  postContentOnFeed:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  commentOnShare:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  likeOnShare:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  disLikeOnShare:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  likeOnComment:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  dislikeOnComment:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: POST 
  getLoggedInEmployee:
      wrapper: BuzzServiceWrapper
      group: buzz
      type: GET 