<?php

/**
 * PluginOAuthClient
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginOAuthClient extends BaseOAuthClient
{
    /**
     * @return string
     */
    public function getGrantTypesString(): string
    {
        return $this->getCommaSeparatedString($this->getGrantTypes());
    }

    /**
     * @return string
     */
    public function getScopeString(): string
    {
        return $this->getCommaSeparatedString($this->getScope());
    }

    /**
     * @param string $spaceSeparatedString
     * @return string
     */
    private function getCommaSeparatedString($spaceSeparatedString): string
    {
        if (is_null($spaceSeparatedString)){
            return '';
        }
        return implode(', ', explode(' ', $spaceSeparatedString));
    }
}
