name: OrangeHRM EXE Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      -   uses: actions/checkout@v2

      -   name: Test
          run: dir

      -   name: Test
          run: dir "C:\Program Files (x86)\NSIS\"

      -   name: Test
          run: dir "C:\Program Files (x86)\NSIS\Plugins"

      -   name: Test
          run: dir "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"
