name: OrangeHRM EXE Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.1'
          tools: composer:v1

      - name: Check env
        run: |
          php -v
          php -m
          composer -v

      - name: Validate composer.json and composer.lock
        run: |
          composer validate -d ./symfony/lib

#       - name: Cache Deps
#         id: cache-deps
#         uses: actions/cache@v2
#         with:
#           path: symfony/lib/vendor
#           key: ${{ runner.os }}-vendor

      - name: Install dependencies
#         if: steps.cache-deps.outputs.cache-hit != 'true'
        run: composer install -d ./symfony/lib

      - name: Dumps the autoloader
        run: composer dump-autoload -o -d ./symfony/lib

      - name: Update mode
        run: |
          cd symfony/
          php symfony orangehrm:change-mode --mode=prod

      - name: Build OrangeHRM
        run: |
          composer global require phing/phing
          composer global require pear/pear
          export PATH=~/.composer/vendor/bin:$PATH
          cd build/
          phing dist
          echo "file_path=$(find dist/ -maxdepth 1 -name '*.zip')" >> $GITHUB_ENV
          PREFIX="dist/"
          echo "file_name=${file_path#$PREFIX}" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm
          path: build/${{ env.file_path }}

  build_exe:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: 'RajithaKumara/orangehrm-nsis-build-assets'
          ref: 'master'
          path: devTools\installer\orangehrm-nsis-build-assets

      - name: Test
        run: dir

      - name: Copy required plugins
        run: copy devTools\installer\orangehrm-nsis-build-assets\x86-ansi_Plugins\*.dll "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"

#      - name: Copy xampp
#        run: copy trimmed-xampp.zip ..

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\"

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\Plugins"

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"

      - name: Extract xampp
        run: |
          cd devTools\installer
          curl -fSL -o trimmed-xampp.zip "https://github.com/RajithaKumara/orangehrm-nsis-build-assets/raw/master/trimmed-xampp.zip"
          7z x trimmed-xampp.zip -oSOURCE -aoa

      - name: Test
        run: |
          cd devTools\installer\orangehrm-nsis-build-assets
          dir

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: orangehrm
          path: devTools\installer\SOURCE

      - name: Test
        run: |
          dir
          cd devTools\installer\SOURCE
          dir

      - name: Test
        run: |
          cd devTools\installer\SPEC
          dir

      - name: Extract OrangeHRM zip
        run: |
          cd devTools\installer\SOURCE
          7z x orangehrm-4.6..zip -aoa

      - name: Build EXE
        run: |
          cd devTools\installer
          makensis SPEC\main.nsi

      - name: Test
        run: |
          cd devTools
          dir

      - name: EXE file name
        run: |
          echo "exe_name=orangehrm-4.6.exe" >> $GITHUB_ENV
          echo "Test"
          echo $Env:exe_name

#       - name: Upload Artifacts
#         uses: actions/upload-artifact@v2
#         with:
#           name: orangehrm-exe
#           path: devTools/orangehrm-4.6.exe

      - name: EXE file name
        run: |
          cd devTools
          dir
          rm installer -r -fo
          dir
          echo 'exe_name<<EOF' >> $GITHUB_ENV
          Get-ChildItem -Path * -Filter *.zip >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "Test"
          echo $Env:exe_name
