name: OrangeHRM EXE Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate -d ./symfony/lib

      - name: Cache Deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: symfony/lib/vendor
          key: ${{ runner.os }}-vendor

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: composer install -d ./symfony/lib

      - name: Dumps the autoloader
        run: composer dump-autoload -o -d ./symfony/lib

      - name: Update mode
        run: |
          cd symfony/
          php symfony orangehrm:change-mode --mode=prod

      - name: Build OrangeHRM
        run: |
          composer global require phing/phing
          composer global require pear/pear
          export PATH=~/.composer/vendor/bin:$PATH
          cd build/
          phing dist
          echo "file_path=$(find dist/ -maxdepth 1 -name '*.zip')" >> $GITHUB_ENV
          PREFIX="dist/"
          echo "file_name=${file_path#$PREFIX}" >> $GITHUB_ENV

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: orangehrm
          path: build/${{ env.file_path }}

  build_exe:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'RajithaKumara/orangehrm-nsis-build-assets'
          ref: 'master'

      - name: Test
        run: dir

      - name: Copy required plugins
        run: copy x86-ansi_Plugins\*.dll "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"

      - name: Copy xampp
        run: copy trimmed-xampp.zip ..

      - name: Test
        run: |
          dir
          cd ..
          dir

      - uses: actions/checkout@v2

      - name: Test
        run: dir

      - name: Copy xampp
        run: |
          copy ..\trimmed-xampp.zip devTools\installer\SOURCE
          cd devTools\installer\SOURCE
          7z e trimmed-xampp.zip

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: orangehrm
          path: devTools\installer\SOURCE

      - name: Test
        run: |
          cd devTools\installer\SOURCE
          dir

      - name: Extract zip
        run: |
          cd devTools\installer\SOURCE
          7z e orangehrm-4.6..zip

      - name: Build EXE
        run: makensis SPEC/main.nsi

      - name: Test
        run: |
          cd devTools
          dir

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\"

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\Plugins"

      - name: Test
        run: dir "C:\Program Files (x86)\NSIS\Plugins\x86-ansi"
