name: 'Parallel Test'

on: [ push, pull_request ]

jobs:
  install:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        testsuite: [ "Admin", "Core", "Pim" ]

    steps:
      - uses: actions/checkout@v2

      - name: Parse Git short hash
        run: echo "git_short_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV

      - name: Install depandancies
        run: |
          sudo systemctl start mysql.service
          cd symfony
          php7.4 -f /usr/bin/composer install
          php7.4 -f /usr/bin/composer dump-autoload -o

      - name: Install OrangeHRM
        run: |
          php installer/cli_install.php 0
          TEST_DB_PREFIX=${{ matrix.testsuite }} php devTools/general/create-test-db.php root

      - name: Run test
        run: |
          TEST_DB_PREFIX=${{ matrix.testsuite }} ./symfony/vendor/bin/phpunit --testsuite ${{ matrix.testsuite }}
